language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage coveralls"
script: coverage run --source=highlander setup.py test
after_success:
    coveralls
